# Copyright 2021 the Tectonic Project
# Licensed under the MIT License

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildDeploy
  displayName: Build and deploy the Docker image

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and deploy the image
      inputs:
        containerRegistry: 'pkgw@DockerHub'
        repository: 'tectonictypesetting/relay-service'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)
          latest
